
INSERT INTO USERS (ID, HOUSE_NUMBER, STREET, CITY, COUNTRY, STATE, ZIP_CODE, EMAIL, FIRST_NAME, LAST_NAME, MIDDLE_NAME) VALUES
(1, 'ADDRESS1', 'ADDRESS2', 'CITY1', 'COUNTRY1', 'STATE1', 'ZIP1', 'EMAIL1', 'FIRSTNAME1', 'LASTNAME1', 'MIDDLENAME1');
