
INSERT INTO USERS (ID, EMAIL, NAME) VALUES
(1, 'EMAIL1', 'NAME1'),
(2, 'EMAIL2', 'NAME2'),
(3, 'EMAIL3', 'NAME3');

INSERT INTO USER_ADDRESSES (USER_ID, HOUSE_NUMBER, STREET, CITY, COUNTRY, STATE, ZIP_CODE) VALUES
(1, 'HOUSE1', 'STREE1', 'CITY1', 'COUNTRY1', 'STATE1', 'ZIP1'),
(1, 'HOUSE2', 'STREE2', 'CITY2', 'COUNTRY2', 'STATE2', 'ZIP2');

INSERT INTO USER_PHONE_NUMBERS(USER_ID, PHONE_NUMBER) VALUES
(1, '051245123'),
(1, '051235123');